// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx59isRIzxSS60ttFduP-XVkeeSB6Yd30',
    appId: '1:1017067702131:web:17eb759ebb7457d7b8a706',
    messagingSenderId: '1017067702131',
    projectId: 'cbc-attendance-2a7d9',
    authDomain: 'cbc-attendance-2a7d9.firebaseapp.com',
    storageBucket: 'cbc-attendance-2a7d9.appspot.com',
    measurementId: 'G-J0LBR36NMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFQi9rJLzK1IPgTQdPRCPYQkx3Vt_V0vo',
    appId: '1:1017067702131:android:d5c4602674d0f0dab8a706',
    messagingSenderId: '1017067702131',
    projectId: 'cbc-attendance-2a7d9',
    storageBucket: 'cbc-attendance-2a7d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgHzQsrkwiPTr5bACZx6-7N2Zj6BhPEIM',
    appId: '1:1017067702131:ios:92aac4ef8acdcc04b8a706',
    messagingSenderId: '1017067702131',
    projectId: 'cbc-attendance-2a7d9',
    storageBucket: 'cbc-attendance-2a7d9.appspot.com',
    iosBundleId: 'com.example.attendanceApp',
  );
}